#!/usr/bin/env bash

cd ~

nix-shell -p git git-crypt gnupg vim --run "

export GPG_TTY=$(tty)
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)

vim ./private_key
gpg --import ./private_key
rm ./private_key

git clone git@github.com:S1M1S/dotfiles.git

cd dotfiles

git-crypt unlock
"
